var express = require('express');
var router = express.Router();
var db = require('../db');

// ---------------
// Database routes
// ---------------

// --- CREATE ----

// Create and persist user with unique userID
router.post('/user', async function (req, res, next) { // tested as get
  const userID = '12345'; //req.body.userID;
  const username = 'test_user'; //req.body.userID;
  const avatar = 'me.png'; //req.body.userID;

  try {
    await db.createUser(userID, username, avatar);
    res.status(200).send('200 | User created.');
  } catch (err) {
    res.status(500).send('500 | ' + err);
  }
});


// --- READ ---

// Get name and avatar
router.get('/user/:user_id', async function (req, res, next) {
  const {user_id} = req.params; 
  
  try {
    var response = await db.getUser(user_id);
    if (response != null) {
      res.send(response);
    } else {
      res.status(404).send('404 | User not found.');
    }
  } catch (err) {
    res.status(502).send('502 | Bad Gateway.');
  }
});

// Get stats from user's previous games
router.get('/user/:user_id/user_stats', async function (req, res, next) {
  const {user_id} = req.params; 
  console.log(user_id);

  try {
    var response = await db.getUserStats(user_id);
    if (response != null) {
      res.send(response);
    } else {
      res.status(404).send('404 | User not found.');
    }
  } catch (err) {
    res.status(502).send('502 | Bad Gateway.');
  }

});


// --- UPDATE ---

// Update username
router.put('/user/:user_id/username', function (req, res, next) {
  res.status(501).send('not implemented');
  // res.status(400).send('Username already exists');
});

// Update avatar
router.put('/user/:user_id/avatar', function (req, res, next) {
  res.status(501).send('not implemented');
});

// Add drawing to user's gallery
router.put('/user/:user_id/session_results', function (req, res, next) {
  res.status(501).send('not implemented');

  /*
    TODO
    - update relevant score (wins/losses as innocent/impostor)
    - add drawing to user's gallery
  */

});

// --- DELETE ---

// Delete user
router.delete('/user/:user_id', function (req, res, next) {
  res.status(501).send('not implemented');
});


// ---------------
// Open AI routes
// ---------------

// Return a unique username generated by openAI
router.get('openai/username/', function (req, res, next) {
  res.status(501).send('not implemented');
});

// Return json object with theme and prompts for both innocents and inkposter
router.get('openai/session_prompts', function (req, res, next) {
  res.status(501).send('not implemented');
});


module.exports = router;
