var express = require('express');
var router = express.Router();
var db = require('../db');

// ---------------
// Database routes
// ---------------

// --- CREATE ----

// Create and persist user with unique userID
router.post('/create_user', function (req, res, next) {
  db.create("new_user").catch(console.dir);
  res.send('User created!');

  // TODO: error code for existing user for given mail
  // res.status(400).send('User already exists');
});


// --- READ ---

// Get all info about user
router.get('/user/:user_id/profile_page', function (req, res, next) {
  res.status(501).send('not implemented');

  // TODO: error code for non-existing user
  //res.status(404).send('User does not exist');
});

// Get name and avatar
router.get('/user/:user_id', function (req, res, next) {
  res.status(501).send('not implemented');

  // TODO: error code for non-existing user
  //res.status(404).send('User does not exist');
});


// --- UPDATE ---

// Update username
router.put('/user/:user_id/username', function (req, res, next) {
  res.status(501).send('not implemented');
  // res.status(400).send('Username already exists');
});

// Update avatar
router.put('/user/:user_id/avatar', function (req, res, next) {
  res.status(501).send('not implemented');
});

// Add drawing to user's gallery
router.put('/user/:user_id/save_session_results', function (req, res, next) {
  res.status(501).send('not implemented');

  /*
    TODO
    - update relevant score (wins/losses as innocent/impostor)
    - add drawing to user's gallery
  */

});

// --- DELETE ---

// Delete user
router.delete('user/:user_id', function (req, res, next) {
  res.status(501).send('not implemented');
});


// ---------------
// Open AI routes
// ---------------

// Return a unique username generated by openAI
router.get('generate_username', function (req, res, next) {
  res.status(501).send('not implemented');
});

// Return json object with theme and prompts for both innocents and inkposter
router.get('generate_session_prompts', function (req, res, next) {
  res.status(501).send('not implemented');
});


module.exports = router;
